apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-istio-cni
  namespace: istio-system
spec:
  allowPrivilegeEscalation: true
  fsGroup:
      rule: RunAsAny
  hostNetwork: true
  runAsUser:
      rule: RunAsAny
  seLinux:
      rule: RunAsAny
  supplementalGroups:
      rule: RunAsAny
  volumes:
  - secret
  - configMap
  - emptyDir
  - hostPath
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-istio-cni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-istio-cni
subjects:
  - kind: ServiceAccount
    name: istio-cni
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-istio-cni
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp-istio-cni
  resources:
  - podsecuritypolicies
  verbs:
  - use
